# 

import sys


def main():

  # Dictionary of suites and parameters, generated by gettitle.py
  suiteParams = {
  "u-bc930" : ["eddyrobertson" , "historical landuse only"] ,
  "u-bd531" : ["eddyrobertson" , "hist-noLu r3 LUMIP UKESM1"] ,
  "u-bd532" : ["eddyrobertson" , "hist-noLu r2 LUMIP UKESM1"] ,
  "u-bd533" : ["eddyrobertson" , "hist-noLu r1 LUMIP UKESM1"] ,
  "u-bf916" : ["eddyrobertson" , "UKESM1.0 vn11.2 LUMIP ssp370-ssp126Lu"] ,
  "u-bf917" : ["eddyrobertson" , "UKESM1.0 vn11.2 LUMIP ssp126-ssp370Lu"] ,
  "u-bf980" : ["eddyrobertson" , "AerChemMIP UKESM1-AMIP piClim-Lu2014"] ,
  "u-bf981" : ["eddyrobertson" , "AerChemMIP UKESM1-AMIP piClim-noLu2014"] ,
  "u-bd531" : ["eddyrobertson" , "hist-noLu r3 LUMIP UKESM1"] ,
  "u-bf965" : ["andywiltshire" , "UKESM1"] ,
  "u-bf967" : ["andywiltshire" , "UKESM1"] ,
  "u-bf968" : ["andywiltshire" , "UKESM1"] ,
  "u-bf938" : ["andywiltshire" , "UKESM1 1%CO2 reverse #1"] ,
  "u-bg203" : ["andywiltshire" , "UKESM1 historical"] ,
  "u-bg204" : ["andywiltshire" , "UKESM1 historical bgc"] ,
  "u-bg205" : ["andywiltshire" , "UKESM1 historical BGC"] ,
  "u-bg206" : ["andywiltshire" , "UKESM1 historical RAD"] ,
  "u-bg207" : ["andywiltshire" , "UKESM1 historical RAD"] ,
  "u-bg208" : ["andywiltshire" , "UKESM1 historical RAD"] ,
  "u-bg512" : ["andywiltshire" , "RFMIP UKESM1-AMIP piClim-4xCO2"] ,
  "u-bf531" : ["fionaoconnor" , "UKESM1-AMIP piClim-control (copy but with extra diags)"] ,
  "u-bf534" : ["fionaoconnor" , "UKESM1-AMIP piClim-control (copy but with extra diags)"] ,
  "u-bf535" : ["fionaoconnor" , "UKESM1-AMIP piClim-control (copy but with extra diags)"] ,
  "u-bg738" : ["fionaoconnor" , "RFMIP UKESM1-AMIP piClim-GHG"] ,
  "u-bf659" : ["gerdfolberth" , "AerChemMIP UKESM1-AMIP piClim-2xNOx"] ,
  "u-bg634" : ["gerdfolberth" , "AerChemMIP UKESM1-AMIP piClim-control"] ,
  "u-bf772" : ["jeffridley" , "HadGEM3-GC3.1 N216ORCA025 PI Control Master for CMIP6 - redistributed ozone all stash except COSP"] ,
  "u-bc235" : ["spencerliddicoat" , "UKESM1 carbon only piControl"] ,
  "u-bc253" : ["spencerliddicoat" , "UKESM1 1%CO2bgc Carbon only"] ,
  "u-be909" : ["spencerliddicoat" , "UKESM1 historical"] ,
  "u-bg017" : ["spencerliddicoat" , "UKESM1 emissions-driven historical"] ,
  "u-bg246" : ["spencerliddicoat" , "UKESM1 esm-piControl including MZ global fix"] ,
  "u-bg258" : ["spencerliddicoat" , "UKESM1 emissions-driven historical CHECK INITIALISATION OF LAND USE"] ,
  "u-bg510" : ["spencerliddicoat" , "UKESM1.0 vn11.2 C4MIP SSP5-8.5-BGC"] ,
  "u-bc590" : ["robinsmith" , "HadGEM3-GC3.1 N96ORCA1-IS 1970 Control for CMIP6"] ,
  "u-bd727" : ["robinsmith" , "HadGEM3-GC3.1 N96ORCA1-IS 1970 abrupt4xCo2 for CMIP6"] ,
  "u-bd729" : ["robinsmith" , "HadGEM3-GC3.1 N96ORCA1-IS 1pctCO2 for CMIP6"] ,
  "u-be760" : ["robinsmith" , "HadGEM3-GC3.1 N96ORCA1-IS 1970 Control for CMIP6"] ,
  "u-bf918" : ["robinsmith" , "UKESM1.0 vn11.2 ScenarioMIP SSP5-8.5"] ,
  "u-bg539" : ["robinsmith" , "bb879 with GM on around Antarctica. UKESM1 N96-ORCA025 without MEDUSA UM11.0"] ,
  "u-be372" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST #1 for CMIP6 : With redistributed ozone - all stash"] ,
  "u-be488" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST #2 for CMIP6 : With redistributed ozone - all stash"] ,
  "u-bf351" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST #1 for CMIP6 : With redistributed ozone - all stash - 1950+"] ,
  "u-bf352" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST #2 for CMIP6 : With redistributed ozone - all stash - 1950+"] ,
  "u-bf353" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST #3 for CMIP6 : With redistributed ozone - all stash - 1950+"] ,
  "u-bf354" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST #4 for CMIP6 : With redistributed ozone - all stash - 1950+"] ,
  "u-bf699" : ["martinandrews" , "Deprecated: HadGEM3-GA7.1 N216 AMIP CMIP6 Master Suite"] ,
  "u-bf741" : ["martinandrews" , "Deprecated HadGEM3-GA7.1 N96 AMIP CMIP6 spinup # 1 : with ozone redistribution"] ,
  "u-bf742" : ["martinandrews" , "deprecated HadGEM3-GA7.1 N96 AMIP CMIP6 spinup # 2 : with ozone redistribution"] ,
  "u-bf743" : ["martinandrews" , "Deprecated HadGEM3-GA7.1 N96 AMIP CMIP6 spinup # 3 : with ozone redistribution"] ,
  "u-bf744" : ["martinandrews" , "deprecated HadGEM3-GA7.1 N96 AMIP CMIP6 spinup # 4 : with ozone redistribution"] ,
  "u-bg101" : ["benjohnson" , "AerChemMIP UKESM1-AMIP piClim-BC"] ,
  "u-bg103" : ["timothyandrews" , "HadGEM3-GC3.1 N216ORCA025 abrupt-4xCO2 for CMIP6"] ,
  "u-bg466" : ["martinandrews" , "HadGEM3-GC3.1 N96ORCA1 HIST run CMIP6 member #1 : 1875+"] ,
  "u-bg468" : ["martinandrews" , "HadGEM3-GC3.1 N96ORCA1 HIST run CMIP6 member #3 : 1875+"] ,
  "u-bg467" : ["martinandrews" , "HadGEM3-GC3.1 N96ORCA1 HIST run CMIP6 member #2 : 1875+"] ,
  "u-bg469" : ["martinandrews" , "HadGEM3-GC3.1 N96ORCA1 HIST run CMIP6 member #4 : 1875+"] ,
  "u-bg470" : ["martinandrews" , "HadGEM3-GC3.1 N96ORCA1 HIST run CMIP6 member #5 : 1875+"] ,
  "u-bg555" : ["timothyandrews" , "CMIP6 DECK HadGEM3-GC3.1 N96ORCA1 abrupt-4xCO2"] ,
  "u-bg567" : ["timothyandrews" , "CMIP6 DECK HadGEM3-GC3.1 N96ORCA1 1pctCO2 #1"] ,
  "u-bg568" : ["timothyandrews" , "CMIP6 DECK HadGEM3-GC3.1 N96ORCA1 1pctCO2 #2"] ,
  "u-bg569" : ["timothyandrews" , "CMIP6 DECK HadGEM3-GC3.1 N96ORCA1 1pctCO2 #3"] ,
  "u-bg570" : ["timothyandrews" , "CMIP6 DECK HadGEM3-GC3.1 N96ORCA1 1pctCO2 #4"] ,
  "u-bg572" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST MASTER for CMIP6 : With redistributed ozone - all stash except COSP"] ,
  "u-bg573" : ["benjohnson" , "RFMIP UKESM1-AMIP piClim-anthro"] ,
  "u-bg574" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST MASTER for CMIP6 : With redistributed ozone - all stash except COSP"] ,
  "u-bg586" : ["martinandrews" , "Deprecated: HadGEM3-GA7.1 N216 AMIP CMIP6 spinup # 1 : with ozone redistribution"] ,
  "u-bg587" : ["martinandrews" , "Deprecated HadGEM3-GA7.1 N216 AMIP CMIP6 spinup # 2 : with ozone redistribution"] ,
  "u-bg588" : ["martinandrews" , "Deprecated HadGEM3-GA7.1 N216 AMIP CMIP6 spinup # 3 : with ozone redistribution"] ,
  "u-bg589" : ["martinandrews" , "Deprecated HadGEM3-GA7.1 N216 AMIP CMIP6 spinup # 4 : with ozone redistribution"] ,
  "u-bg617" : ["timothyandrews" , "CMIP6 DECK HadGEM3-GC3.1 N216ORCA025 abrupt-4xCO2"] ,
  "u-bg618" : ["timothyandrews" , "CMIP6 DECK HadGEM3-GC3.1 N216ORCA025 1pctCO2"] ,
  "u-bg881" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST # 1, 1988+ : With redistributed ozone - all stash except COSP"] ,
  "u-bg882" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST # 2, 1988+ : With redistributed ozone - all stash except COSP"] ,
  "u-bg883" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST # 3, 1988+ : With redistributed ozone - all stash except COSP"] ,
  "u-bg884" : ["martinandrews" , "HadGEM3-GC3.1 N216ORCA025 HIST # 4, 1988+ : With redistributed ozone - all stash except COSP"] ,
  "u-bh010" : ["martinandrews" , "HadGEM3-GA7.1 N216 AMIP CMIP6 spinup # 1 test: with ozone redistribution"] ,
  "u-bh109" : ["martinandrews" , "HadGEM3-GA7.1 N96 AMIP CMIP6 spinup # 1 test: with ozone redistribution"] ,
  "u-bh114" : ["martinandrews" , "HadGEM3-GA7.1 N216 AMIP CMIP6 spinup # 1 test: with ozone redistribution"] ,
  "u-aq281" : ["timbradshaw" , "HadGEM3-GC3.1 N216ORCA025 PI Control for CMIP6"] ,
  "u-bf467" : ["catherinehardacre" , "UKESM1.0-beta pre-industrial control, UM11.2. PIC with rcwater mod, DMSO mod, rc stomata mod, rc crop mod and Strat-Trop nucleation bug fix."] ,
  "u-bf590" : ["catherinehardacre" , "UKESM1.0-beta pre-industrial control, UM11.2. PIC with rcwater mod and Strat-Trop nucleation bug fix."] ,
  "u-bf785" : ["catherinehardacre" , "UKESM1"] ,
  "u-bf786" : ["catherinehardacre" , "UKESM1"] ,
  }

  nodesTotal = 0
  print "User     Nodes             Task                Queued? Owner            Suite title"
  for line in sys.stdin:
    # Emsure that the line contains the details about a job (starts with xxxxxx.xcs00).
    if ".xcs" not in line:
      continue
    
    # Extract the number of nodes and jobname (of the form foo.bar.suite).
    items = line.split()
    nodes = int(items[5])
    jobName = items[3]

    # Extract the jobname (of the form foo.bar.suite).
    jobName = items[3]
    
    # Extract the username.
    user = items[1]

    # Extract the queueing indicator.
    queueLabel = items[9]

    # Extract the suite from the jobname, then get its parameters.
    suite = jobName.split('.')[2]
    if suite in suiteParams:
      title = suiteParams[suite][1]
      owner = suiteParams[suite][0]
    else:
      title = ""
      owner = ""
      print "No parameters for ", suite

    # Output results for this suite.
    print("{0:<8s} {1:3d}  {2:>35s} {3:<2s}   {4:<15s} {5:<50s}").format(user,
      nodes, jobName, queueLabel, owner, title)
    nodesTotal += nodes

  print("Total number of nodes {}\n").format(nodesTotal)


if __name__ == '__main__':
  main()
